### ISSUE TITLE
Sort Lists

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#22]
In GitLab by @brunocalado on Feb 25, 2021, 19:38

## Summary
Make possible to enable auto sort.

Auto sort moves
![image](https://gitlab.com/asacolips-projects/foundry-mods/pbta/uploads/e1dafb50b25d89c17dc6a917b1fb83f1/image.png)

Auto sort conditions
![image](https://gitlab.com/asacolips-projects/foundry-mods/pbta/uploads/c78a6f94e0385163e66fc7dd9f0bb203/image.png)

## Labels (do-not-change)

/cc @Asacolips

**Comment by mclemente** [comment]
This was completed on PbtA 0.9 https://github.com/asacolips-projects/pbta/commit/4228413bf649044288c885e0e07012792d65945b
