### ISSUE TITLE
[Feature Request] Playbook Attr granting also grants attr descriptions when set.

### ISSUE THREAD

**Issue by philote** [asacolips-projects/pbta#225]
For Attribute grants from playbooks: 
- I can see some cases where it would be nice to be able to set the attribute description as well as its value on a playbook grant.

**Comment by mclemente** [comment]
How big do you need the field to look like? Is this enough?
![image](https://github.com/asacolips-projects/pbta/assets/5288872/a949a277-864e-4a68-955d-5b140497b636)

**Comment by philote** [comment]
That should work for the things that I was envisioning.
