### ISSUE TITLE
Bad CSS

### ISSUE THREAD

**Issue by brunocalado** [asacolips-projects/pbta#234]
The CSS from the pbta system mess up the Foundry CSS. It's hard to read the config and other dialogs.

PBTA
![image](https://github.com/asacolips-projects/pbta/assets/4999783/05786fbc-c4ad-48fa-9c18-868a91bf0752)
![image](https://github.com/asacolips-projects/pbta/assets/4999783/e7114578-0c02-4761-bcea-76c99e69e957)

Other systems
![image](https://github.com/asacolips-projects/pbta/assets/4999783/d74a3a77-d065-4e63-8dd2-f6a4da1ca6d3)
Light
![image](https://github.com/asacolips-projects/pbta/assets/4999783/6bb12230-58b8-493b-a70a-bd231a342204)

**Comment by mclemente** [comment]
Just noticed the fix I've applied doesn't work with the image popout of #224, which I've originally fixed.

So expect this to be fixed everywhere except there 🤦
