### ISSUE TITLE
Text Overflow

### ISSUE THREAD

**Issue by brunocalado** [asacolips-projects/pbta#240]
I think this maybe a pbta system problem, I'm not sure. The text overflow over the tabs. 

This happens with the the module [FW](https://github.com/Rangertheman/fwrpg-for-pbta). You just need to create an agent and add more than 3 lines.

![image](https://github.com/asacolips-projects/pbta/assets/4999783/9bf01425-8228-43a7-bbfa-ff96321a50b2)

Link: [https://github.com/Rangertheman/fwrpg-for-pbta/issues/30](https://github.com/Rangertheman/fwrpg-for-pbta/issues/30)

**Comment by mclemente** [comment]
Just made a new release that should fix these issues. Let me know if you're still having these issues or something similar pops up.

**Comment by brunocalado** [comment]
> Just made a new release that should fix these issues. Let me know if you're still having these issues or something similar pops up.

Worked. Thank you.
