### ISSUE TITLE
Question about tags and possible bug

### ISSUE THREAD

**Issue by fe5hua** [asacolips-projects/pbta#251]
Hi, I noticed that tags are a thing, but the only place I find them are the tag settings and items.
Is it possible to add tags to characters esp. NPCs. The documentation shows a tags field on a npc character sheet screenshot and being able to define tags for characters in the settings indicates that it is somehow possible.
Do I need to define a special tags field in the config-sheet?

The text input in the item sheet does not seem to properly work. I look different from the on in the tag settings and it is not interactive in any way the label indicates.

thanks.

**Comment by mclemente** [comment]
There is support for tags on actor sheets, but the base system itself doesn't display them anywhere.

You can display them by subclassing the PbtA Actor Sheet and overriding `activateListeners` like this

```js
// FooActorSheet extends pbta.applications.actor.PbtaActorSheet
activateListeners(html) {
  super.activateListeners(html);
  const tagify = this._activateTagging(html);
  tagify.on("edit:start", ({ detail: { tag, data } }) => game.pbta.utils.TagHandler.onEdit(tagify, { tag, data }));
}
```

And adding this to the html:
```html
<input name='system.tags' class='tags' placeholder='{{localize "PBTA.TagsPlaceholder"}}' value='{{ system.tags }}'/>
```

> The text input in the item sheet does not seem to properly work. I look different from the on in the tag settings and it is not interactive in any way the label indicates.

What browser are you using? It works just fine for me on Firefox/Chrome.

**Comment by mclemente** [comment]
It has been a while since I've played with the tags on actor sheets, so I'm sorry it didn't work out for you, I thought it would work fine for you.

What game are you trying to create on the system? The main reason I haven't worked on improving Tags for actors is that I'm not aware of any games that absolutely *need* it to exist.
